// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: titip.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_titip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_titip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_titip_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type EsiFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartPos      int32                  `protobuf:"varint,1,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	EndPos        int32                  `protobuf:"varint,2,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	Src           string                 `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Alt           string                 `protobuf:"bytes,4,opt,name=alt,proto3" json:"alt,omitempty"`
	OnError       string                 `protobuf:"bytes,5,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`
	MaxDepth      uint32                 `protobuf:"varint,6,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	FallbackBody  []byte                 `protobuf:"bytes,8,opt,name=fallback_body,json=fallbackBody,proto3" json:"fallback_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EsiFragment) Reset() {
	*x = EsiFragment{}
	mi := &file_titip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EsiFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsiFragment) ProtoMessage() {}

func (x *EsiFragment) ProtoReflect() protoreflect.Message {
	mi := &file_titip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsiFragment.ProtoReflect.Descriptor instead.
func (*EsiFragment) Descriptor() ([]byte, []int) {
	return file_titip_proto_rawDescGZIP(), []int{1}
}

func (x *EsiFragment) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *EsiFragment) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *EsiFragment) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *EsiFragment) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

func (x *EsiFragment) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

func (x *EsiFragment) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *EsiFragment) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *EsiFragment) GetFallbackBody() []byte {
	if x != nil {
		return x.FallbackBody
	}
	return nil
}

// VariantInfo stores metadata for a specific Vary header combination
type VariantInfo struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	VariantKey           string                   `protobuf:"bytes,1,opt,name=variant_key,json=variantKey,proto3" json:"variant_key,omitempty"`                                                                              // Unique storage subkey e.g., "gzip_en"
	VaryHeaders          map[string]string        `protobuf:"bytes,2,rep,name=vary_headers,json=varyHeaders,proto3" json:"vary_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Matched request headers e.g. {"Accept-Encoding": "gzip"}
	StatusCode           int32                    `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseHeaders      map[string]*HeaderValues `protobuf:"bytes,4,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Etag                 string                   `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModifiedUnixNano int64                    `protobuf:"varint,6,opt,name=last_modified_unix_nano,json=lastModifiedUnixNano,proto3" json:"last_modified_unix_nano,omitempty"`
	RawBodySize          uint32                   `protobuf:"varint,7,opt,name=raw_body_size,json=rawBodySize,proto3" json:"raw_body_size,omitempty"`
	CompressedBodySize   uint32                   `protobuf:"varint,8,opt,name=compressed_body_size,json=compressedBodySize,proto3" json:"compressed_body_size,omitempty"`
	EsiFragments         []*EsiFragment           `protobuf:"bytes,10,rep,name=esi_fragments,json=esiFragments,proto3" json:"esi_fragments,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VariantInfo) Reset() {
	*x = VariantInfo{}
	mi := &file_titip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantInfo) ProtoMessage() {}

func (x *VariantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_titip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantInfo.ProtoReflect.Descriptor instead.
func (*VariantInfo) Descriptor() ([]byte, []int) {
	return file_titip_proto_rawDescGZIP(), []int{2}
}

func (x *VariantInfo) GetVariantKey() string {
	if x != nil {
		return x.VariantKey
	}
	return ""
}

func (x *VariantInfo) GetVaryHeaders() map[string]string {
	if x != nil {
		return x.VaryHeaders
	}
	return nil
}

func (x *VariantInfo) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *VariantInfo) GetResponseHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *VariantInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *VariantInfo) GetLastModifiedUnixNano() int64 {
	if x != nil {
		return x.LastModifiedUnixNano
	}
	return 0
}

func (x *VariantInfo) GetRawBodySize() uint32 {
	if x != nil {
		return x.RawBodySize
	}
	return 0
}

func (x *VariantInfo) GetCompressedBodySize() uint32 {
	if x != nil {
		return x.CompressedBodySize
	}
	return 0
}

func (x *VariantInfo) GetEsiFragments() []*EsiFragment {
	if x != nil {
		return x.EsiFragments
	}
	return nil
}

// CacheMetadata stores the primary URL index and variant registry
type CacheMetadata struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	PrimaryKey         string                  `protobuf:"bytes,1,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	VaryHeaderNames    []string                `protobuf:"bytes,2,rep,name=vary_header_names,json=varyHeaderNames,proto3" json:"vary_header_names,omitempty"`                                    // e.g. ["Accept-Encoding", "Accept-Language"]
	Variants           map[string]*VariantInfo `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Keyed by normalized vary values
	CreatedAtUnixNano  int64                   `protobuf:"varint,4,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	ExpiresAtUnixNano  int64                   `protobuf:"varint,5,opt,name=expires_at_unix_nano,json=expiresAtUnixNano,proto3" json:"expires_at_unix_nano,omitempty"`
	StaleUntilUnixNano int64                   `protobuf:"varint,6,opt,name=stale_until_unix_nano,json=staleUntilUnixNano,proto3" json:"stale_until_unix_nano,omitempty"`
	Tags               []string                `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	IsSoftPurged       bool                    `protobuf:"varint,8,opt,name=is_soft_purged,json=isSoftPurged,proto3" json:"is_soft_purged,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CacheMetadata) Reset() {
	*x = CacheMetadata{}
	mi := &file_titip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheMetadata) ProtoMessage() {}

func (x *CacheMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_titip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheMetadata.ProtoReflect.Descriptor instead.
func (*CacheMetadata) Descriptor() ([]byte, []int) {
	return file_titip_proto_rawDescGZIP(), []int{3}
}

func (x *CacheMetadata) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *CacheMetadata) GetVaryHeaderNames() []string {
	if x != nil {
		return x.VaryHeaderNames
	}
	return nil
}

func (x *CacheMetadata) GetVariants() map[string]*VariantInfo {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *CacheMetadata) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *CacheMetadata) GetExpiresAtUnixNano() int64 {
	if x != nil {
		return x.ExpiresAtUnixNano
	}
	return 0
}

func (x *CacheMetadata) GetStaleUntilUnixNano() int64 {
	if x != nil {
		return x.StaleUntilUnixNano
	}
	return 0
}

func (x *CacheMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CacheMetadata) GetIsSoftPurged() bool {
	if x != nil {
		return x.IsSoftPurged
	}
	return false
}

var File_titip_proto protoreflect.FileDescriptor

const file_titip_proto_rawDesc = "" +
	"\n" +
	"\vtitip.proto\x12\x05titip\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xe3\x01\n" +
	"\vEsiFragment\x12\x1b\n" +
	"\tstart_pos\x18\x01 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x02 \x01(\x05R\x06endPos\x12\x10\n" +
	"\x03src\x18\x03 \x01(\tR\x03src\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\tR\x03alt\x12\x19\n" +
	"\bon_error\x18\x05 \x01(\tR\aonError\x12\x1b\n" +
	"\tmax_depth\x18\x06 \x01(\rR\bmaxDepth\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\rR\ttimeoutMs\x12#\n" +
	"\rfallback_body\x18\b \x01(\fR\ffallbackBody\"\xde\x04\n" +
	"\vVariantInfo\x12\x1f\n" +
	"\vvariant_key\x18\x01 \x01(\tR\n" +
	"variantKey\x12F\n" +
	"\fvary_headers\x18\x02 \x03(\v2#.titip.VariantInfo.VaryHeadersEntryR\vvaryHeaders\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12R\n" +
	"\x10response_headers\x18\x04 \x03(\v2'.titip.VariantInfo.ResponseHeadersEntryR\x0fresponseHeaders\x12\x12\n" +
	"\x04etag\x18\x05 \x01(\tR\x04etag\x125\n" +
	"\x17last_modified_unix_nano\x18\x06 \x01(\x03R\x14lastModifiedUnixNano\x12\"\n" +
	"\rraw_body_size\x18\a \x01(\rR\vrawBodySize\x120\n" +
	"\x14compressed_body_size\x18\b \x01(\rR\x12compressedBodySize\x127\n" +
	"\resi_fragments\x18\n" +
	" \x03(\v2\x12.titip.EsiFragmentR\fesiFragments\x1a>\n" +
	"\x10VaryHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aW\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.titip.HeaderValuesR\x05value:\x028\x01\"\xbc\x03\n" +
	"\rCacheMetadata\x12\x1f\n" +
	"\vprimary_key\x18\x01 \x01(\tR\n" +
	"primaryKey\x12*\n" +
	"\x11vary_header_names\x18\x02 \x03(\tR\x0fvaryHeaderNames\x12>\n" +
	"\bvariants\x18\x03 \x03(\v2\".titip.CacheMetadata.VariantsEntryR\bvariants\x12/\n" +
	"\x14created_at_unix_nano\x18\x04 \x01(\x03R\x11createdAtUnixNano\x12/\n" +
	"\x14expires_at_unix_nano\x18\x05 \x01(\x03R\x11expiresAtUnixNano\x121\n" +
	"\x15stale_until_unix_nano\x18\x06 \x01(\x03R\x12staleUntilUnixNano\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12$\n" +
	"\x0eis_soft_purged\x18\b \x01(\bR\fisSoftPurged\x1aO\n" +
	"\rVariantsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.titip.VariantInfoR\x05value:\x028\x01B+Z)github.com/indragunawan/titip/proto;protob\x06proto3"

var (
	file_titip_proto_rawDescOnce sync.Once
	file_titip_proto_rawDescData []byte
)

func file_titip_proto_rawDescGZIP() []byte {
	file_titip_proto_rawDescOnce.Do(func() {
		file_titip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_titip_proto_rawDesc), len(file_titip_proto_rawDesc)))
	})
	return file_titip_proto_rawDescData
}

var file_titip_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_titip_proto_goTypes = []any{
	(*HeaderValues)(nil),  // 0: titip.HeaderValues
	(*EsiFragment)(nil),   // 1: titip.EsiFragment
	(*VariantInfo)(nil),   // 2: titip.VariantInfo
	(*CacheMetadata)(nil), // 3: titip.CacheMetadata
	nil,                   // 4: titip.VariantInfo.VaryHeadersEntry
	nil,                   // 5: titip.VariantInfo.ResponseHeadersEntry
	nil,                   // 6: titip.CacheMetadata.VariantsEntry
}
var file_titip_proto_depIdxs = []int32{
	4, // 0: titip.VariantInfo.vary_headers:type_name -> titip.VariantInfo.VaryHeadersEntry
	5, // 1: titip.VariantInfo.response_headers:type_name -> titip.VariantInfo.ResponseHeadersEntry
	1, // 2: titip.VariantInfo.esi_fragments:type_name -> titip.EsiFragment
	6, // 3: titip.CacheMetadata.variants:type_name -> titip.CacheMetadata.VariantsEntry
	0, // 4: titip.VariantInfo.ResponseHeadersEntry.value:type_name -> titip.HeaderValues
	2, // 5: titip.CacheMetadata.VariantsEntry.value:type_name -> titip.VariantInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_titip_proto_init() }
func file_titip_proto_init() {
	if File_titip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_titip_proto_rawDesc), len(file_titip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_titip_proto_goTypes,
		DependencyIndexes: file_titip_proto_depIdxs,
		MessageInfos:      file_titip_proto_msgTypes,
	}.Build()
	File_titip_proto = out.File
	file_titip_proto_goTypes = nil
	file_titip_proto_depIdxs = nil
}
